# -*- coding: utf-8 -*-
"""Menú de ficha médica .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfIf5sS2bmmW1VGRfgE_38y_p4_H9nus
"""

ficha_paciente = []

ficha_medico = ()

while True:
  print('¿Cual opcion desea?:')
  print('a: Ficha medica:')
  print('b: Registro')
  print('c: Salir')
  opcion = input()
  if opcion == 'a':
     print('***Ficha Medica***')
     print('Ingrese nombre de paciente:')
     nombre = input()
     ficha_paciente.append(nombre)
     print('Ingrese diagnostico de paciente:')
     diagnostico = input()
     ficha_paciente.append(diagnostico)
     print('Fecha:')
     fecha = input()
     ficha_paciente.append(fecha)
  elif opcion == 'b':
       print(ficha_paciente)
  elif opcion == 'c':
       break

ficha_paciente = []

ficha_pa = []

while True:
  print('¿Cual opcion desea?:')
  print('a: Ficha medica:')
  print('b: Registro')
  print('c: Salir')
  opcion = input()
  if opcion == 'a':
     print('***Ficha Medica***')
     print('Ingrese nombre de paciente:')
     nombre = input()
     ficha_pa.append(nombre)
     print('Ingrese diagnostico de paciente:')
     diagnostico = input()
     ficha_pa.append(diagnostico)
     print('Fecha:')
     fecha = input()
     ficha_pa.append(fecha)
  elif opcion == 'b':
       for i in range(0, len(ficha_pa)):
        if (i % 3) == 0:
          ficha_paciente.append((ficha_pa[i], ficha_pa[i+1], ficha_pa[i+2]))

       print(ficha_paciente)
  elif opcion == 'c':
       break